set nocompatible
filetype off

"Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'
Plug 'vim-airline/vim-airline'
Plug 'guns/xterm-color-table.vim'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()
"run :PlugInstall 	# install plugins
"run :PlugUpdate	# update plugins

let g:airline_powerline_fonts = 1

syntax on
noswapfile
set hidden

" Show partial commands in the last line of the screen
set showcmd

" Quickly time out on keycodes, but never on mappings
set notimeout ttimeout ttimeoutlen=200

set hlsearch
"set incsearch alreade set in tpope/vim-sensible

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Set certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline

" Ask to save changes instead of error
set confirm

" Use visual bell instead of beeping on error
set visualbell
set t_vb=

" Enable use of the mouse for all modes
set mouse=a

" Set command window height to 2 lines, avoid "press <Enter> to continue"
set cmdheight=2

" Use <F11> to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>

" Break line at a word boundry
set linebreak

set shiftwidth=2
set softtabstop=2
set expandtab

" Map Y to act like D and C, i.e. yank until EOL
map Y y$

" Highlight trailing whitespace
" Cool! Applications > Accessories > Character Map
" This one is from Common
set list listchars=tab:\ \ ,trail:•

let mapleader = "-"

noremap <leader>ev :edit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Split navigations
" Ctrl-j move to the split below... etc.
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set t_Co=256

colorscheme default

set number
set relativenumber
highlight LineNr ctermbg=234 ctermfg=240

" Highlight the current line
" cterm=NONE removes underline!
set cursorline
highlight CursorLine ctermbg=234 cterm=NONE
highlight CursorLineNr ctermbg=234 ctermfg=11
"autocmd InsertEnter * highlight CursorLine ctermbg=#000050 ctermfg=fg
"autocmd InsertLeave * highlight CursorLine ctermbg=#005000 ctermfg=fg

" Always highlight column 80 so it's easier to see
"autocmd BufWinEnter * highlight ColorColumn cterbg=darkred
set colorcolumn=80
highlight colorcolumn ctermbg=234

" Redraw only when needed (i.e. dont' redraw when executing a macro)
set lazyredraw

" highlight matching [{()}] when cursor placed on start/end character
set showmatch

